Add hw3
Donfa1con/made_2019_cpp pull request #3
Opened 2019-11-05 15:11 UTC by Donfa1con

2019-11-06 12:03 UTC, smirnov-vs requested changes

2019-11-06 12:03 UTC, smirnov-vs commented on 03/analyzer/analyzer.hpp
> +    std::vector<std::function<void(const std::string&)>> on_string_callbacks;
функциональные типы стоит вынести в using

2019-11-06 12:03 UTC, smirnov-vs commented on 03/analyzer/analyzer.cpp
> +void Analyzer::add_on_string_token_callback(std::function<void(const std::string&)> on_string) {
функторы могут быть большими, в общем случае по значению передавать не очень

2019-11-06 12:03 UTC, smirnov-vs commented on 03/analyzer/analyzer.cpp
> +bool Analyzer::is_number(std::string& token) const {
токен изменять не надо

2019-11-06 12:03 UTC, smirnov-vs commented on 03/analyzer/analyzer.cpp
> +    }
получается, что стартовые колбэки могут быть вызваны после финишных. Вероятность точно не нулевая

2019-11-07 16:08 UTC, smirnov-vs commented on 03/analyzer/analyzer.cpp
> +    }
теперь финишные могут быть вызваны раньше промежуточных обработчиков
старые .get вызываются еще раз

стоит заметить, что async на каждый колбэк это очень медленно будет для реальных задач

2019-11-08 16:05 UTC, Donfa1con commented on 03/analyzer/analyzer.cpp
> +    }
Как поступают в реальных задачах при большом количестве колбэков? Создают отдельный тред с объектом который хотим обработать и там вызывают функции последовательно или как-то иначе?

2019-11-10 15:31 UTC, smirnov-vs commented on 03/analyzer/analyzer.cpp
> +    }
самый оптимальный вариант, создать тредпул под количество процессоров и закидывать его этими задачами

2019-11-10 15:32 UTC, smirnov-vs approved these changes
привет, я принял задачу

2019-11-12 07:20 UTC, merged