Add hw8: Vector
Donfa1con/made_2019_cpp pull request #9
Opened 2020-01-06 20:38 UTC by Donfa1con

2020-01-08 14:50 UTC, smirnov-vs requested changes

2020-01-08 14:50 UTC, smirnov-vs commented on 08/vector.hpp
> +    void push_back(value_type&& value) {
работает неправильно

2020-01-08 14:50 UTC, smirnov-vs commented on 08/vector.hpp
> +        data_[i++] = *current++;
слева сырая память, так нельзя делать

2020-01-08 14:50 UTC, smirnov-vs commented on 08/vector.hpp
> +    copy(copied.data_, data_, size_);
аналогично

2020-01-08 15:55 UTC, Donfa1con commented on 08/vector.hpp
> +    copy(copied.data_, data_, size_);
Тут я вызываю construct в copy

2020-01-10 11:52 UTC, smirnov-vs commented on 08/vector.hpp
> +    copy(copied.data_, data_, size_);
ага, увидел

2020-01-10 11:52 UTC, smirnov-vs approved these changes

2020-01-10 11:57 UTC, merged